### PR TITLE
Add scripts to facilitate running automation during releases

### PR DESCRIPTION
**Pull request by shahzaibj**
For MSAL release run the msal release automation script as follows: 
`.\MsalReleaseAutomation.ps1 -msalVersion 2.0.6-RC1 -labSecret <secret-value>`

For Broker release run the broker release automation script as follows: 
`.\BrokerReleaseAutomation.ps1 -labSecret <secret-value> -authenticatorApkPath '<path-to-apk>' -companyPortalApkPath '<path-to-apk>'`

### CODE REVIEW

**Comment by iambmelt** [comment]
> The script can be run as follows:
> 
> `.\MsalReleaseAutomation.ps1 -msalVersion 2.0.6-RC1 -labSecret <secret-value>`

Thanks for this PR, @shahzaibj -- I think we would also benefit from a having a [`docs/`](https://github.com/AzureAD/android-complete/tree/master/docs) page capturing
- "How to Run Automation" -> pointer to this script
- "Acquiring the Lab Secret" -> Relevant steps, list of IdWeb Groups, who has access (employees)

**Comment by shahzaibj** [comment]
> > The script can be run as follows:
> > `.\MsalReleaseAutomation.ps1 -msalVersion 2.0.6-RC1 -labSecret <secret-value>`
> 
> Thanks for this PR, @shahzaibj -- I think we would also benefit from a having a [`docs/`](https://github.com/AzureAD/android-complete/tree/master/docs) page capturing
> 
> * "How to Run Automation" -> pointer to this script
> * "Acquiring the Lab Secret" -> Relevant steps, list of IdWeb Groups, who has access (employees)

Sure  @iambmelt I will add that in soon

**Comment by AdamBJohnsonx** [comment]
Generic question: I'm assuming .ps1 files are PowerShell given the syntax.  Is that correct?  Should be pretty simple to convert to bourne or python from my reading.  Do you want to do that, or should we make a task for this?

**Comment by shahzaibj** [comment]
> Generic question: I'm assuming .ps1 files are PowerShell given the syntax. Is that correct? Should be pretty simple to convert to bourne or python from my reading. Do you want to do that, or should we make a task for this?

Yes these are powershell. We can make a task to convert to Python if needed.

**Comment by shahzaibj** [comment]
> > > The script can be run as follows:
> > > `.\MsalReleaseAutomation.ps1 -msalVersion 2.0.6-RC1 -labSecret <secret-value>`
> > 
> > 
> > Thanks for this PR, @shahzaibj -- I think we would also benefit from a having a [`docs/`](https://github.com/AzureAD/android-complete/tree/master/docs) page capturing
> > 
> > * "How to Run Automation" -> pointer to this script
> > * "Acquiring the Lab Secret" -> Relevant steps, list of IdWeb Groups, who has access (employees)
> 
> Sure @iambmelt I will add that in soon

@iambmelt Added here: https://github.com/AzureAD/android-complete/tree/shahzaibj/msal-release-automation-script/docs/Automation

JFYI, The doc on lab setup is mostly just copied from OneNote page `LabAutomationSetup`

**Review by iambmelt — APPROVED** [review]
Love it, thanks @shahzaibj!

**Review by rpdome — APPROVED** [review]
I tried running the msal script in Powershell on OSX - the script seems to be running fine (with some failing test cases).
Added a prerequisite instruction for that as well.

Regarding the OneNote page `LabAutomationSetup`. I'd suggest scraping that out (maybe put a link to this page) and maintain everything here instead. We shouldn't have to maintain the same file in two places.

**Comment by shahzaibj** [comment]
> I tried running the msal script in Powershell on OSX - the script seems to be running fine (with some failing test cases).
> Added a prerequisite instruction for that as well.
> 
> Regarding the OneNote page `LabAutomationSetup`. I'd suggest scraping that out (maybe put a link to this page) and maintain everything here instead. We shouldn't have to maintain the same file in two places.

Yeah that sounds good. I'll do that. Thanks @rpdome for trying on OSX!

**Pull request merged**
